### ISSUE TITLE
Unexpected `g:wordmotion_prefix` behaviour for text objects

### ISSUE THREAD

**Issue by deiwin** [chaoren/vim-wordmotion#3]
I configured `let g:wordmotion_prefix = ","` in my vimrc and expected text object bindings to change from `iw` and `aw` to `i,w` and `a,w`. Because I see `i` and `a` as the _verbs_ and `w` or `,w` as the _nouns_ that the _verbs_ operate on. Instead, the bindings were changed to `,iw` and `,aw`.

I'm using the following as a workaround:
```vim
let g:wordmotion_mappings = {
	\ 'w' : ',w',
	\ 'e' : ',e',
	\ 'b' : ',b',
	\ 'ge' : ',ge',
	\ 'iw' : 'i,w',
	\ 'aw' : 'a,w'
  \ }
```

**Comment by chaoren** [comment]
Should be fixed with 9962f07cbc07f27cd6848e673fe8f2292c0661f7. Please verify.

**Comment by chaoren** [comment]
Also, `aw` stands for "a word", 'iw' stands for "inner word", so they're not verbs.

/pedantry

**Comment by deiwin** [comment]
Thanks for the quick response! The change seems to be working well. Although, I'm afraid you missed the [`MAPPINGS` part of the doc](https://github.com/chaoren/vim-wordmotion/blob/master/doc/wordmotion.txt#L31) that also needs to be changed.

As for the verb vs qualifier (which I see you used to describe `i` and `a` in your commit, code), you are absolutely right. I wouldn't dismiss this as pedantry, though. Being able to talk about these concepts in a clear and consistent way means also being able to better reason about these concepts. This, in turn, helps us build more practical and useful tools on top of these concepts. Luckily this time you got the gist of what I was getting at without me having to be correct.

**Comment by chaoren** [comment]
Thanks. Now that's fix too with 3ab8303718f855d72f3f14fbe089d144b4f2794d.
